l_spanish:
# l_spanish:
# l_german:
# l_french:
# l_russian:
# l_simp_chinese:
# l_korean:

 compose_verse_decision:0 "Compose Verse"
 compose_verse_decision_desc:0 "To write poetry is important to one's self, spiritually and emotionally. It is time I once take up quill and create."
 compose_verse_decision_tooltip:0 "Poetry can be an interesting way for self-reflection and emotional expression and creativity. It can help us create new solutions for challenges, while also offering a type of therapeutic outlet."
 compose_verse_decision_confirm:0 "Bring me ink!"

 compose_poetry.001.t:0 "To Compose"
 compose_poetry.001.desc:0 "Poetry is an important component of religious expression in [ROOT.Char.GetFaith.GetAdjectiveNoTooltip] practice, and it has been far too long since I have last composed. I sit at my study, writing implements ready, but I still question if I should begin."
 compose_poetry.001.a:0 "Let the writing begin!"
 compose_poetry.001.b:0 "Ah! Damn this writer's block!"
 
 compose_poetry.002.t:0 "Writing Verse"
 compose_poetry.002.desc:0 "All good poetry must have a point, a subject. Before I even begin it would be best for me to determine what the theme of my poem shall be."
 compose_poetry.002.brave:0 "The merit of battle!"
 compose_poetry.002.craven:0 "A description of battle, from afar of course."
 compose_poetry.002.calm:0 "Just sitting, enjoying the sun"
 compose_poetry.002.wrathful:0 "Fire... or maybe breaking things."
 compose_poetry.002.chaste:0 "The joy of pure, transcendental love."
 compose_poetry.002.lustful:0 "Enjoying the embrace of another."
 compose_poetry.002.content:0 "Living a simple life."
 
 compose_poetry.004.desc:0 "With the planning done, I put pen to paper and begin to write, a few ideas float around in my mind about the imagery."
 compose_poetry.004.a:0 "My poem will be bound to the images of nature."
 compose_poetry.004.b:0 "I will ground my descriptions in mundane life."
 compose_poetry.004.c:0 "I think a stream of consciousness will fit best"
 compose_poetry.004.lunatic:0 "Anything the voices tell me!"

 compose_poetry.006.desc:0 "Ah! My work is done! But what's art if it can't be appreciated? I must know to whom I will distribute my poem."
 compose_poetry.006.a:0 "The [ROOT.Char.GetFaith.PriestNeuterPlural] will appreciate it."
 compose_poetry.006.b:0 "It will be read in public!"
 compose_poetry.006.c:0 "My vassals will enjoy a good poem."
 compose_poetry.006.d:0 "Those that wish to read it can seek it out themselves."
 
 compose_poetry.007.desc:0 "Those that have read my work have already praised it's quality, I'm certain more will come, but for now, I am done."
 compose_poetry.007.poet:0 "Another on for my collection!"
 compose_poetry.007.a:0 "That was eventful."
 
 romantic_modifier:0 "Wrote a Romantic Poem"
 realist_modifier:0 "Wrrote a Realist Poem"
 postmodern_modifier:0 "Wrote a Postmodern Poem"
 nation_poetry_modifier:0 "Poem is about my nation"
 poetry_form_modifier:0 "Poem alters form"
 poetry_traditional_modifier:0 "Poem is conventional"
 poetry_clergy_modifier:0 "Poem distributed among Clergy"
 poetry_public_modifier:0 "Poem distributed among Public"
 poetry_nobles_modifier:0 "Poem distributed among Vassals"
 poetry_dont_modifier:0 "Poem not distributed"
 reveler_poetry_modifier:0 "Poem is about Partying"
 seduce_poetry_modifier:0 "Poem is about love"
 lunatic_poetry_modifier:0 "THE VOICES"
 
 lustful_poetry_modifier:0 "Lustful Poetry"
 chaste_poetry_modifier:0 "Chaste Poetry"
 gluttonous_poetry_modifier:0 "Gluttonous Poetry"
 temperate_poetry_modifier:0 "Temperate Poetry"
 greedy_poetry_modifier:0 "Greedy Poetry"
 generous_poetry_modifier:0 "Generous Poetry"
 lazy_poetry_modifier:0 "Lazy Poetry"
 diligent_poetry_modifier:0 "Diligent Poetry"
 wrathful_poetry_modifier:0 "Wrathful Poetry"
 calm_poetry_modifier:0 "Calm Poetry"
 patient_poetry_modifier:0 "Patient Poetry"
 impatient_poetry_modifier:0 "Impatient Poetry"
 arrogant_poetry_modifier:0 "Arrogant Poetry"
 humble_poetry_modifier:0 "Humble Poetry"
 deceitful_poetry_modifier:0 "Deceitful Poetry"
 honest_poetry_modifier:0 "Honest Poetry"
 craven_poetry_modifier:0 "Craven Poetry"
 brave_poetry_modifier:0 "Brave Poetry"
 shy_poetry_modifier:0 "Shy Poetry"
 gregarious_poetry_modifier:0 "Gregarious Poetry"
 ambitious_poetry_modifier:0 "Ambitious Poetry"
 content_poetry_modifier:0 "Content Poetry"
 arbitrary_poetry_modifier:0 "Arbitrary Poetry"
 just_poetry_modifier:0 "Just Poetry"
 cynical_poetry_modifier:0 "Cynical Poetry"
 zealous_poetry_modifier:0 "Zealous Poetry"
 paranoid_poetry_modifier:0 "Paranoid Poetry"
 trusting_poetry_modifier:0 "Trusting Poetry"
 compassionate_poetry_modifier:0 "Compassionate Poetry"
 callous_poetry_modifier:0 "Callous Poetry"
 sadistic_poetry_modifier:0 "Sadistic Poetry"
 stubborn_poetry_modifier:0 "Stubborn Poetry"
 fickle_poetry_modifier:0 "Fickle Poetry"
 eccentric_poetry_modifier:0 "Eccentric Poetry"
 vengeful_poetry_modifier:0 "Vengeful Poetry"
 forgiving_poetry_modifier:0 "Forgiving Poetry"
 
 doctrine_parameter_poetry_slam_enabled:0 "Rulers can Compose Literary Works"
 doctrine_parameter_compose_epic_religious_enabled:0 "Rulers can Commission Epics"